module.exports = quotes = [
    'Making it through a full 24 hours without a single misstep is called “Reaganing”',
    'Human empathy is as useless as the Winter Olympics',
    'Have you ever considered becoming the celebrity face of the Republican Party?',
    'I\'m not a creative type like you, with your work sneakers and left-handedness.',
    'Factories provide three things this country desperately needs: jobs, pride, and material for Bruce Springsteen songs.',
    'I like you. You have the boldness of a much younger woman.',
    'Weird in a good way. Like going to the gym drunk.',
    'Okay, in my defense, every April 22nd I honor Richard Nixon\'s death by getting drunk and making some unpopular decisions.',
    'Men need alcohol. It gives us the ability to hit on women and then later when we\'re married, to tune them out.',
    'can promise you this weekend will be filled with staring out windows while holding a glass of scotch.',
    'We produce more failed pilots than the French Air Force.',
    'Never go with a hippie to a second location',
    'I once claimed, “I am God” during a deposition',
    'Good God, Lemon!',
    'How gay, Banks? On a scale of bear-hunting to hunting bears.',
    'Money can\'t buy happiness. It is happiness.',
    'When it comes to hair, no one is more bitchy than conservative males.',
    'Come on, Lemon. What do we elites do when we screw up? We pretend it never happened and give ourselves a giant bonus.',
    'Ambition is the willingness to kill the things you love and eat them to survive. Haven\'t you ever read my throw pillow?',
    'I have to talk to Rachel Maddow. Only one of us can have this haircut.',
    'Lemon, you look terrible, and I once watched you eat oysters while you had a cold.',
    'Every time I meet a new person, I figure out how I\'m gonna fight \'em.',
    'You know what family means to me, Lemon? Resentment. Guilt. Anger. Easter egg hunts that turn into knife fights.',
    'Jack: I have faith in things I can see, and buy, and regulate. Capitalism is my religion.',
    'The Italians have a saying, Lemon: “Keep your friends close, and your enemies closer.” And although they\'ve never won a war or mass-produced a decent car, in this case, they\'re right.',
    'Business doesn\'t get me down. Business gets me off.',
    'Those shoes are definitely bi-curious.',
    'Well, it\'s business drunk. It\'s like rich drunk. Either way, it\'s legal to drive.',
    'Lemon, the grown-up dating world is like your haircut. Sometimes, weird triangles occur.',
    'In order to save this network, I have to destroy it. Just like BP heroically did when they tried to lubricate the Gulf of Mexico.',
    'A guaranteed disaster. Like eating a burrito before sex.',
    'There are no bad ideas; there are only great ideas that go horribly wrong.',
    'We all have ways of coping. I use sex and awesomeness.'
];
